# Generated by Django 4.1.2 on 2023-08-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gas_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersupportinteraction",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Resolved", "Resolved")],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
